quarkus.http.port=8080
quarkus.http.root-path=/nvm/api

# ??? DATABASE ????????????????????????????????????????????????
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/nvm_cars
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=10

# ??? HIBERNATE ???????????????????????????????????????????????

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
# ??? LOG ?????????????????????????????????????????????????????
quarkus.log.level=INFO
quarkus.log.category."org.hibernate".level=WARN


generator.domain.model.path=modello\\nvmCarsCorretto.xmi
generator.java.output.path=C:\\Users\\jaorr\\IdeaProjects\\nvmcars\\src\\main\\java
generator.sql.output=schema\\schema.sql
generator.model.package=org.nvm.cars.model
generator.repository.package=org.nvm.cars.repository
generator.service.package=org.nvm.cars.service
generator.controller.package=org.nvm.cars.controller
generator.dto.package=org.nvm.cars.dto
