
CREATE TABLE IF NOT EXISTS clienti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    data_di_nascita TIMESTAMP NOT NULL,
    numero VARCHAR(255) NOT NULL,
    credenziali_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS titolari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    data_di_nascita TIMESTAMP NOT NULL,
    numero VARCHAR(255) NOT NULL,
    regione_sociale VARCHAR(255) NOT NULL,
    partita_iva VARCHAR(255) NOT NULL,
    codice_fiscale VARCHAR(255) NOT NULL,
    credenziali_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS attivita_registrate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    descrizione VARCHAR(255),
    numero VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    titolare_id BIGINT NOT NULL,
    indirizzo_id BIGINT NOT NULL,
    listino_servizi_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS macchine_registrate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    targa VARCHAR(255) NOT NULL,
    marca VARCHAR(255) NOT NULL,
    modello VARCHAR(255) NOT NULL,
    anno TIMESTAMP NOT NULL,
    cliente_id BIGINT NOT NULL,
    riga_prenotazione_id BIGINT,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS listino_servizi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    attivita_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS servizi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    descrizione VARCHAR(255),
    prezzo DECIMAL NOT NULL,
    durata INTEGER NOT NULL,
    listino_servizi_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS prenotazioni (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data_creazione TIMESTAMP NOT NULL,
    stato VARCHAR(255) NOT NULL,
    cliente_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS disponibilita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data_ora_inizio TIMESTAMP NOT NULL,
    data_ora_fine TIMESTAMP NOT NULL,
    posti_disponibili INTEGER NOT NULL,
    servizio_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS credenziali (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(12) NOT NULL,
    email VARCHAR(255) NOT NULL,
    titolare_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS indirizzo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    via VARCHAR(255) NOT NULL,
    civico VARCHAR(255) NOT NULL,
    citta VARCHAR(255) NOT NULL,
    cap VARCHAR(255) NOT NULL,
    provincia VARCHAR(255) NOT NULL,
    latitudine DECIMAL,
    longitudine DECIMAL,
    attivita_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS righe_prenotazione (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    note VARCHAR(255) NOT NULL,
    automobile_id BIGINT,
    servizio_id BIGINT NOT NULL,
    prenotazione_id BIGINT NOT NULL,
    disponiblita_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


ALTER TABLE clienti
    ADD CONSTRAINT fk_clienti_credenziali_id
    FOREIGN KEY (credenziali_id) REFERENCES credenziali(id);

ALTER TABLE titolari
    ADD CONSTRAINT fk_titolari_credenziali_id
    FOREIGN KEY (credenziali_id) REFERENCES credenziali(id);

ALTER TABLE titolari
    ADD CONSTRAINT uq_titolari_regione_sociale
    UNIQUE (regione_sociale);

ALTER TABLE titolari
    ADD CONSTRAINT uq_titolari_partita_iva
    UNIQUE (partita_iva);

ALTER TABLE titolari
    ADD CONSTRAINT uq_titolari_codice_fiscale
    UNIQUE (codice_fiscale);

ALTER TABLE attivita_registrate
    ADD CONSTRAINT fk_attivita_registrate_titolare_id
    FOREIGN KEY (titolare_id) REFERENCES titolari(id)
    ON DELETE CASCADE;

ALTER TABLE attivita_registrate
    ADD CONSTRAINT fk_attivita_registrate_indirizzo_id
    FOREIGN KEY (indirizzo_id) REFERENCES indirizzo(id)
    ON DELETE CASCADE;

ALTER TABLE attivita_registrate
    ADD CONSTRAINT fk_attivita_registrate_listino_servizi_id
    FOREIGN KEY (listino_servizi_id) REFERENCES listino_servizi(id)
    ON DELETE CASCADE;

ALTER TABLE attivita_registrate
    ADD CONSTRAINT uq_attivita_registrate_email
    UNIQUE (email);

ALTER TABLE macchine_registrate
    ADD CONSTRAINT fk_macchine_registrate_cliente_id
    FOREIGN KEY (cliente_id) REFERENCES clienti(id)
    ON DELETE CASCADE;

ALTER TABLE macchine_registrate
    ADD CONSTRAINT fk_macchine_registrate_riga_prenotazione_id
    FOREIGN KEY (riga_prenotazione_id) REFERENCES righe_prenotazione(id)
    ON DELETE SET NULL;

ALTER TABLE macchine_registrate
    ADD CONSTRAINT uq_macchine_registrate_targa
    UNIQUE (targa);

ALTER TABLE listino_servizi
    ADD CONSTRAINT fk_listino_servizi_attivita_id
    FOREIGN KEY (attivita_id) REFERENCES attivita_registrate(id)
    ON DELETE CASCADE;

ALTER TABLE servizi
    ADD CONSTRAINT fk_servizi_listino_servizi_id
    FOREIGN KEY (listino_servizi_id) REFERENCES listino_servizi(id)
    ON DELETE CASCADE;

ALTER TABLE prenotazioni
    ADD CONSTRAINT fk_prenotazioni_cliente_id
    FOREIGN KEY (cliente_id) REFERENCES clienti(id)
    ON DELETE CASCADE;

ALTER TABLE disponibilita
    ADD CONSTRAINT fk_disponibilita_servizio_id
    FOREIGN KEY (servizio_id) REFERENCES servizi(id)
    ON DELETE CASCADE;

ALTER TABLE credenziali
    ADD CONSTRAINT fk_credenziali_titolare_id
    FOREIGN KEY (titolare_id) REFERENCES titolari(id);

ALTER TABLE credenziali
    ADD CONSTRAINT uq_credenziali_username
    UNIQUE (username);

ALTER TABLE credenziali
    ADD CONSTRAINT uq_credenziali_password
    UNIQUE (password);

ALTER TABLE credenziali
    ADD CONSTRAINT uq_credenziali_email
    UNIQUE (email);

ALTER TABLE indirizzo
    ADD CONSTRAINT fk_indirizzo_attivita_id
    FOREIGN KEY (attivita_id) REFERENCES attivita_registrate(id)
    ON DELETE CASCADE;

ALTER TABLE righe_prenotazione
    ADD CONSTRAINT fk_righe_prenotazione_automobile_id
    FOREIGN KEY (automobile_id) REFERENCES macchine_registrate(id)
    ON DELETE SET NULL;

ALTER TABLE righe_prenotazione
    ADD CONSTRAINT fk_righe_prenotazione_servizio_id
    FOREIGN KEY (servizio_id) REFERENCES servizi(id)
    ON DELETE RESTRICT;

ALTER TABLE righe_prenotazione
    ADD CONSTRAINT fk_righe_prenotazione_prenotazione_id
    FOREIGN KEY (prenotazione_id) REFERENCES prenotazioni(id)
    ON DELETE CASCADE;

ALTER TABLE righe_prenotazione
    ADD CONSTRAINT fk_righe_prenotazione_disponiblita_id
    FOREIGN KEY (disponiblita_id) REFERENCES disponibilita(id)
    ON DELETE RESTRICT;


